#pragma once

#include <stdio.h>
#include <string.h>
#include <iostream>
#include <math.h>
#include <cmath>
#include <cstdio>
#include <vector>
#include <algorithm>
#include <optional>
#include <memory>
#include <queue>
#include <list>
#include <stack>
#include <assert.h>
#include <unordered_set>
#include <unordered_map>
#include <mutex>
#include <condition_variable>
#include <thread>
#include <fstream>
#include <future>
#include <tuple>

using std::cout;
using std::cin;
using std::endl;
using std::vector;
using std::boolalpha;
using std::ostream;
using std::unique_ptr;
using std::queue;
using std::list;
using std::stack;
using std::unordered_set;
using std::unordered_map;
using std::condition_variable;
using std::mutex;
using std::unique_lock;
using std::thread;
using std::fstream;
using std::ifstream;
using std::ios;
using std::string;
using std::future;
using std::async;
using std::pair;
using std::priority_queue;
using std::tuple;